//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seocake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int StatisticsId { get; set; }
        public string WebmasterName { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> PartnersId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
