//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seocake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int PartnerId { get; set; }
        public string Description { get; set; }
        public string ReferalHref { get; set; }
    }
}
