//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seocake.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seocakeConnectionString : DbContext
    {
        public seocakeConnectionString()
            : base("name=seocakeConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Partner> Partners { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Soft> Softs { get; set; }
        public DbSet<Statistic> Statistics { get; set; }
        public DbSet<Vocabluary> Vocabluaries { get; set; }
    }
}
