//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public Access()
        {
            this.Users = new HashSet<User>();
        }
    
        public int AccessId { get; set; }
        public string AccessDesc { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
